<a href="https://colab.research.google.com/github/darshanjoshi16/DataAnalyticsMiniProjects/blob/main/Udemy%20Courses%20Analysis/Udemy_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Analytics Mini Project - 1**

Dataset: Udemy Course Dataset

In this notebook, we will analyse the udemy course dataset and will try to give the insights from the dataset by applying the various data analytics methods.

**Section 1: Importing the libraries**

In [2]:
#importing the libraries to perform the task
import pandas as pd
from google.colab import files
import io

**Section 2: Importing the Data**

In [3]:
#using files module we will take csv file as the input
uploading = files.upload()

#creating the dataframe and reading csv and  using IO library for converting into data frame
df = pd.read_csv(io.BytesIO(uploading['Udemy_Courses.csv']))

Saving Udemy_Courses.csv to Udemy_Courses.csv

**Section 3: Exploring the Data**

In [4]:
#printing the whole dataset
print(df)

      course_id                                       course_title  is_paid  \
0        288942  #1 Piano Hand Coordination: Play 10th Ballad i...     True
1       1170074  #10 Hand Coordination - Transfer Chord Ballad ...     True
2       1193886  #12 Hand Coordination: Let your Hands dance wi...     True
3       1116700  #4 Piano Hand Coordination: Fun Piano Runs in ...     True
4       1120410  #5  Piano Hand Coordination:  Piano Runs in 2 ...     True
...         ...                                                ...      ...
3677     328960  Your Own Site in 45 Min: The Complete Wordpres...     True
3678     552700    Your Second Course on Piano: Two Handed Playing     True
3679     631754  Zend Framework 2: Learn the PHP framework ZF2 ...     True
3680    1225194  Zoho Books Gestion Financière d'Entreprise pas...    False
3681     964478                Zombie Apocalypse Photoshop Actions     True

     price  num_subscribers  num_reviews  num_lectures               level  \
0       35             3137           18            68          All Levels
1       75             1593            1            41  Intermediate Level
2       75              482            1            47  Intermediate Level
3       75              850            3            43  Intermediate Level
4       75              940            3            32  Intermediate Level
...    ...              ...          ...           ...                 ...
3677   120             1566           29            36          All Levels
3678    70             1018           12            22      Beginner Level
3679    40              723          130            37          All Levels
3680  Free              229            0            33          All Levels
3681    50               12            1            15          All Levels

     content_duration   published_timestamp              subject
0           1.5 hours  2014-09-18T05:07:05Z  Musical Instruments
1              1 hour  2017-04-12T19:06:34Z  Musical Instruments
2           1.5 hours  2017-04-26T18:34:57Z  Musical Instruments
3              1 hour  2017-02-21T23:48:18Z  Musical Instruments
4             37 mins  2017-02-21T23:44:49Z  Musical Instruments
...               ...                   ...                  ...
3677          4 hours  2015-04-20T22:15:17Z      Web Development
3678          5 hours  2015-10-26T20:04:21Z  Musical Instruments
3679        6.5 hours  2015-11-11T18:55:45Z      Web Development
3680          2 hours  2017-05-26T16:45:55Z     Business Finance
3681        1.5 hours  2016-09-26T22:19:48Z       Graphic Design

[3682 rows x 11 columns]

**Section 4: Taking the insights using the questions**

**(1). What are the all subjects for which Udemy is offering the courses?**

In [5]:
#it will show different subjects for which courses are being offered
df.subject.unique()

array(['Musical Instruments', 'Business Finance', 'Graphic Design',
       'Web Development'], dtype=object)

**(2). Which subjects has the maximum number of courses?**

In [6]:
#it will search the counts into subject column
df.subject.value_counts()

Web Development        1200
Business Finance       1199
Musical Instruments     680
Graphic Design          603
Name: subject, dtype: int64

**(3). Show all the courses which are free of cost.**

In [7]:
df[df.is_paid == False]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
41,286070,5 lecciones que todo guitarrista debe tomar,False,Free,4452,263,14,Beginner Level,1 hour,2014-08-23T05:08:14Z,Musical Instruments
49,696630,"7 Ways A Beginner Guitarist Can Sound Better, ...",False,Free,4529,193,7,Beginner Level,36 mins,2015-12-21T18:50:50Z,Musical Instruments
57,955914,A beginner`s guide to fingerpicking and strumm...,False,Free,3481,29,20,Beginner Level,2 hours,2016-09-13T21:51:59Z,Musical Instruments
67,270976,A how to guide in HTML,False,Free,7318,205,8,Beginner Level,35 mins,2014-08-10T20:19:10Z,Web Development
74,1214144,¡Triunfar en La Bolsa de Valores No Requiere d...,False,Free,338,7,6,Beginner Level,1 hour,2017-05-30T14:30:12Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3620,552598,WordPress in under an hour - Create/manage you...,False,Free,6474,86,15,All Levels,1 hour,2015-07-15T00:21:56Z,Web Development
3638,1068590,Wordpress Website Mastery 2017,False,Free,5181,64,22,Beginner Level,2.5 hours,2017-01-18T17:01:40Z,Web Development
3652,752706,Write quicker HTML5 and CSS 3; productivity ha...,False,Free,13016,286,15,All Levels,1.5 hours,2016-03-03T17:45:31Z,Web Development
3674,1257976,Your First 10 Guitar Lessons - Learn how to pl...,False,Free,924,4,18,Beginner Level,1 hour,2017-06-29T00:29:36Z,Musical Instruments
3680,1225194,Zoho Books Gestion Financière d'Entreprise pas...,False,Free,229,0,33,All Levels,2 hours,2017-05-26T16:45:55Z,Business Finance

**(4). Show all the courses which are paid.**

In [8]:
df[df.is_paid == True]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments
...,...,...,...,...,...,...,...,...,...,...,...
3676,498488,Your First Successful Forex Trades - With Case...,True,200,1079,34,16,All Levels,2.5 hours,2015-05-26T20:48:48Z,Business Finance
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3678,552700,Your Second Course on Piano: Two Handed Playing,True,70,1018,12,22,Beginner Level,5 hours,2015-10-26T20:04:21Z,Musical Instruments
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26T22:19:48Z,Graphic Design

**(5). Which are the top selling courses?**

In [10]:
#it will sort the tuples as per the number of subscriber in the ascending mode
df.sort_values('num_subscribers',ascending=False)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
2290,1223240,Learn Pirates of the Caribbean by Ear on the P...,True,20,0,0,6,All Levels,32 mins,2017-05-22T17:14:43Z,Musical Instruments
1267,1258666,Financial Statement Auditing Cycles,True,50,0,0,9,Intermediate Level,2 hours,2017-06-29T23:20:10Z,Business Finance
2070,1215926,Kickstarter success in 5 easy steps,True,20,0,0,12,All Levels,31 mins,2017-05-16T14:55:28Z,Business Finance
1931,1247992,Introduction to Project Management for Finance...,True,50,0,0,9,Beginner Level,2 hours,2017-07-03T21:40:32Z,Business Finance
3165,1087466,Stop Creditors from Harassing you and Avoid Ba...,True,20,0,0,7,Beginner Level,37 mins,2017-02-02T16:22:37Z,Business Finance

**(6). Which are the least selling courses?**

In [11]:
#it will sort the tuples as per the number of subscriber in the descending mode
df.sort_values('num_subscribers', ascending=True)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
649,1233314,Building a Balanced Scorecard,True,50,0,0,11,Intermediate Level,2 hours,2017-07-03T21:38:22Z,Business Finance
3259,1232282,The Cash Flow Statement - An Introduction,True,50,0,0,10,Beginner Level,1.5 hours,2017-06-28T16:05:51Z,Business Finance
3261,1275872,The Complete Adobe Spark Course,True,150,0,0,29,All Levels,2 hours,2017-07-03T17:39:57Z,Graphic Design
910,726314,Create Beautiful Image Maps for Your Website,True,20,0,0,8,Intermediate Level,37 mins,2016-01-18T17:56:36Z,Graphic Design
3328,715476,The Cuckoo Strategy to get European Funding,True,160,0,0,6,All Levels,1 hour,2016-01-06T02:38:23Z,Business Finance
...,...,...,...,...,...,...,...,...,...,...,...
3316,764164,The Complete Web Developer Course 2.0,True,200,114512,22412,304,All Levels,30.5 hours,2016-03-08T22:28:36Z,Web Development
640,173548,Build Your First Website in 1 Week with HTML5 ...,False,Free,120291,5924,30,Beginner Level,3 hours,2014-04-08T16:21:30Z,Web Development
3385,625204,The Web Developer Bootcamp,True,200,121584,27445,342,All Levels,43 hours,2015-11-02T21:13:27Z,Web Development
776,59014,Coding for Entrepreneurs Basic,False,Free,161029,279,27,Beginner Level,3.5 hours,2013-06-09T15:51:55Z,Web Development
2230,41295,Learn HTML5 Programming From Scratch,False,Free,268923,8629,45,All Levels,10.5 hours,2013-02-14T07:03:41Z,Web Development

**(7). Show all the courses of Web development where the price is less than 500**

In [16]:
#using and operator we are doing the comparision
df[(df.subject == 'Web Development') & (df.price < '500')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
11,64605,1 Hour CSS,True,100,18324,333,16,Beginner Level,1 hour,2013-07-09T20:27:14Z,Web Development
12,64422,1 Hour HTML,True,200,16212,514,20,Beginner Level,1 hour,2013-07-09T03:16:26Z,Web Development
13,63612,1 Hour JavaScript,True,200,22999,602,18,Beginner Level,1 hour,2013-07-04T15:27:02Z,Web Development
14,72262,1 hour jQuery,True,100,5456,133,25,Beginner Level,1 hour,2013-08-03T14:20:52Z,Web Development
24,975916,17 Complete JavaScript projects explained st...,True,185,327,26,106,Beginner Level,9.5 hours,2016-10-26T14:03:38Z,Web Development
...,...,...,...,...,...,...,...,...,...,...,...
3666,969170,XSD :basics for beginners,True,35,755,0,7,All Levels,42 mins,2016-09-27T18:01:26Z,Web Development
3667,968278,XSLT :basics for beginners,True,35,877,6,7,All Levels,32 mins,2016-09-27T15:14:59Z,Web Development
3670,560996,You can create Incredible Websites with HTML C...,True,100,11892,50,28,All Levels,2.5 hours,2015-09-12T01:35:41Z,Web Development
3677,328960,Your Own Site in 45 Min: The Complete Wordpres...,True,120,1566,29,36,All Levels,4 hours,2015-04-20T22:15:17Z,Web Development
3679,631754,Zend Framework 2: Learn the PHP framework ZF2 ...,True,40,723,130,37,All Levels,6.5 hours,2015-11-11T18:55:45Z,Web Development

**(8). List out all the courses which are related to ReactJS.**

In [18]:
#converting the content of course title column into  string and checking the ReactJS is among the string or not
df[df.course_title.str.contains('ReactJS')]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
616,645714,Build Apps with ReactJS: The Complete Course,True,40,1433,145,34,All Levels,5.5 hours,2015-10-22T21:07:29Z,Web Development
2148,978850,Learn by Example : ReactJS,True,50,1496,37,74,Beginner Level,7.5 hours,2016-12-27T19:39:12Z,Web Development
2303,590406,Learn ReactJS: Code Like A Facebook Developer,True,20,1948,72,45,Intermediate Level,5 hours,2015-08-24T20:31:54Z,Web Development
2938,1016388,Projects In ReactJS - The Complete React Learn...,True,50,947,108,56,Intermediate Level,8 hours,2016-11-22T04:21:03Z,Web Development
2997,647564,React: Learn ReactJS Fundamentals for Front-En...,True,55,1993,55,26,All Levels,4 hours,2016-06-06T15:29:42Z,Web Development
2999,764042,ReactJS and Flux: Learn By Building 10 Projects,True,60,1723,258,60,All Levels,11 hours,2016-02-18T18:18:12Z,Web Development
3000,543346,ReactJS Course: Learn JavaScript Library Used ...,True,50,1018,33,41,Intermediate Level,3 hours,2015-07-07T13:42:32Z,Web Development

**(9). List out the courses published in year 2016**

In [20]:
#converting the timestamp column using the datetime functionality and different methods
df['published_timestamp'] = pd.to_datetime(df.published_timestamp)
df['Year'] = df['published_timestamp'].dt.year
df[df.Year == 2016]

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,Year
7,768028,* An Integrated Approach to the Fundamentals o...,True,200,134,14,123,All Levels,5.5 hours,2016-03-15 17:23:07+00:00,Business Finance,2016
9,738910,[Value Investing] Where White People Keep Thei...,True,200,2715,70,20,Expert Level,4 hours,2016-05-25 21:04:41+00:00,Business Finance,2016
18,897162,101 Awesome Rockabilly Guitar Licks,True,40,407,64,33,Intermediate Level,2.5 hours,2016-08-10 20:58:18+00:00,Musical Instruments,2016
22,759972,150 Rock Guitar Licks You MUST Know,True,45,252,14,21,All Levels,4.5 hours,2016-02-19 17:24:14+00:00,Musical Instruments,2016
24,975916,17 Complete JavaScript projects explained st...,True,185,327,26,106,Beginner Level,9.5 hours,2016-10-26 14:03:38+00:00,Web Development,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
3664,968292,XPATH :basics for beginners,True,40,878,6,8,All Levels,37 mins,2016-09-27 15:20:47+00:00,Web Development,2016
3665,968304,XQUERY :basics for beginners,True,40,937,2,6,All Levels,38 mins,2016-09-27 15:26:05+00:00,Web Development,2016
3666,969170,XSD :basics for beginners,True,35,755,0,7,All Levels,42 mins,2016-09-27 18:01:26+00:00,Web Development,2016
3667,968278,XSLT :basics for beginners,True,35,877,6,7,All Levels,32 mins,2016-09-27 15:14:59+00:00,Web Development,2016
3681,964478,Zombie Apocalypse Photoshop Actions,True,50,12,1,15,All Levels,1.5 hours,2016-09-26 22:19:48+00:00,Graphic Design,2016

**(10). What are the max numbers of subscribers for each level of courses?**

In [21]:
#using groupby method and grouping on the based of level and giving the maximum value
df.groupby('level')['num_subscribers'].max()

level
All Levels            268923
Beginner Level        161029
Expert Level            5172
Intermediate Level     29167
Name: num_subscribers, dtype: int64